export const theme = {
  colors: {
    primary: '#16a34a',        // Fresh NearMart Emerald Green
    primaryDark: '#15803d',
    primaryLight: '#dcfce7',
    merchantPrimary: '#2563eb', // Blue theme for Merchant
    merchantDark: '#1d4ed8',
    merchantLight: '#dbeafe',
    background: '#f8fafc',
    card: '#ffffff',
    text: '#0f172a',
    textPrimary: '#0f172a',
    textSecondary: '#64748b',
    textMuted: '#94a3b8',
    border: '#e2e8f0',
    borderFocus: '#16a34a',
    danger: '#dc2626',
    dangerLight: '#fee2e2',
    warning: '#f59e0b',
    warningLight: '#fef3c7',
    success: '#16a34a',
    successLight: '#dcfce7',
    surface: '#ffffff',
    overlay: 'rgba(15, 23, 42, 0.6)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    base: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
  },
  borderRadius: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    full: 9999,
  },
  typography: {
    hero: { fontSize: 28, fontWeight: '700' as const, lineHeight: 34 },
    title: { fontSize: 22, fontWeight: '700' as const, lineHeight: 28 },
    subtitle: { fontSize: 18, fontWeight: '600' as const, lineHeight: 24 },
    body: { fontSize: 15, fontWeight: '400' as const, lineHeight: 22 },
    bodyBold: { fontSize: 15, fontWeight: '600' as const, lineHeight: 22 },
    small: { fontSize: 13, fontWeight: '400' as const, lineHeight: 18 },
    smallBold: { fontSize: 13, fontWeight: '600' as const, lineHeight: 18 },
    caption: { fontSize: 11, fontWeight: '500' as const, lineHeight: 14 },
    button: { fontSize: 16, fontWeight: '600' as const, lineHeight: 20 },
  },
  shadows: {
    sm: {
      shadowColor: '#0f172a',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#0f172a',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    lg: {
      shadowColor: '#0f172a',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 16,
      elevation: 6,
    },
  },
};